### ISSUE TITLE
 How to get the parameters on the URL？

### ISSUE THREAD

**Issue by damiaozi** [ericwooley/react-nativeish#13]
I use react-navigation Do interface jump.
but,now，I want to get the parameters on the URL。
How to get the parameters on the URL?

**Comment by ericwooley** [comment]
This is really a react-navigation issue, I would open an issue there for more help. But here is what I know:

https://reactnavigation.org/docs/guides/web

There docs are not very helpful. You might have to look at the source and see how the website works. Or just parse them yourself. https://stackoverflow.com/questions/979975/how-to-get-the-value-from-the-get-parameters

**Comment by damiaozi** [comment]
thank you
