### ISSUE TITLE
react-web vs react-native-web

### ISSUE THREAD

**Issue by liorix** [ericwooley/react-nativeish#16]
Hi,

Great job!
Was wondering if you considered using react-web instead of react-native-web? 
https://github.com/taobaofed/react-web

Thanks,
Lior

**Comment by ericwooley** [comment]
I have not, though I did try react-primitives for a little.

i had not yet come across that project, can you explain the benefits of react web vs react-native-web?

The biggest reason I am inclined to stick with react-native-web is because CRA has support for it out of the box.

**Comment by liorix** [comment]
I have to say that I'm not sure. 

I was looking at your project and was interested to learn more about react-native-web. When I looked for more information I saw a recommendation to use react-web.

When I read about it I saw that react-web implemented more components than react-native-web and that a big company is behind it (Alibaba). 

But I really don't  much about both libraries.

**Comment by liorix** [comment]
I just saw this library as well, which looks interesting: https://github.com/Microsoft/reactxp

**Comment by ericwooley** [comment]
Well, if people want to use react-web, they would have to eject CRA and switch too it, but it wouldn't be too hard and should be relatively seamless to switch
